In [2]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 17 15:34:32 2017

@author: justinwu
"""

import numpy as np
from scipy import linalg
A = np.array([[1,3,5],[2,5,1],[2,3,8]])
print(A)
print(linalg.inv(A)) #inverse matrix
print(A.dot(linalg.inv(A))) #matrix.dot(inversed matrix) = unit matrix

[[1 3 5]
 [2 5 1]
 [2 3 8]]
[[-1.48  0.36  0.88]
 [ 0.56  0.08 -0.36]
 [ 0.16 -0.12  0.04]]
[[ 1.00000000e+00 -1.11022302e-16 -5.55111512e-17]
 [ 3.05311332e-16  1.00000000e+00  1.87350135e-16]
 [ 2.22044605e-16 -1.11022302e-16  1.00000000e+00]]


In [3]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 17 15:56:48 2017

@author: justinwu
"""

import numpy as np
from scipy import linalg as la
A = np.array([[1,2],[3,4]])
print(A)
print(la.det(A))

[[1 2]
 [3 4]]
-2.0


In [4]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Oct 18 17:14:57 2017

@author: justinwu
"""

import numpy as np 
from scipy import linalg as la
A = np.array([[1,5,2],[2,4,1],[3,6,2]])
lna,v=la.eig(A)
l1,l2,l3=lna
print(l1,l2,l3)
print(v)
print(v[:,0])
print(v[:,1])
print(v[:,2])
print('--------------')
v1=np.array(v[:,0]).T
print(v1)
print(linalg.norm(A.dot(v1)-l1*v1))

(7.957916204910751+0j) (-1.2576647056775323+0j) (0.29974850076678317+0j)
[[-0.5297175  -0.90730751  0.28380519]
 [-0.44941741  0.28662547 -0.39012063]
 [-0.71932146  0.30763439  0.87593408]]
[-0.5297175  -0.44941741 -0.71932146]
[-0.90730751  0.28662547  0.30763439]
[ 0.28380519 -0.39012063  0.87593408]
--------------
[-0.5297175  -0.44941741 -0.71932146]
2.6645352591003757e-15
